name: Build and Push All Services

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - ArticleService
          - CacheService
          - CommentService
          - DraftService
          - NewsletterService
          - ProfanityService
          - PublisherService
          - SubscriberService

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]'):latest
          VERSION_TAG=ghcr.io/${{ github.repository_owner }}/$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]'):${{ github.run_number }}

          # Build from the repository root using the specific Dockerfile
          docker build -t $IMAGE_NAME -t $VERSION_TAG -f ${{ matrix.service }}/Dockerfile .

          # Push both tags
          docker push $IMAGE_NAME
          docker push $VERSION_TAG
